### ISSUE TITLE
'Play' does not open CS:GO installed on another drive.

### ISSUE THREAD

**Issue by frnaky** [lemonpole/liga-public#76] opened 2024-10-09 06:52 UTC
## Describe the bug

Clicking on play does not launch CS:GO, which is installed on my D: drive.

Changing Steam path in settings to 'C:\Program Files (x86)\Steam' OR 'D:\SteamLibrary' doesn't fix the issue.

## To Reproduce

1. Go to 'Dashboard'
2. Click on 'Play'
3. Game does not launch

## Expected behavior

Expected that game would launch

## Technical Information

- OS: Windows 11
- App Version: v3.0.0-beta.7

**Comment by lemonpole** [comment] 2024-10-09 11:29
Hey thanks for taking the time to try out my app. I'll be working on fixing this for the next release. 

Same root cause as #73.

**Comment by lemonpole** [comment] 2024-10-09 21:12
Pushed a fix for this in `beta.8`.

I also added the ability to manual set the game installation location if the app can't figure it out on its own.

![steam-path](https://github.com/user-attachments/assets/75538711-2871-4efa-8415-34abb19ceca4)

**Closed by lemonpole** 2024-10-09 21:12 UTC
Labels: bug
